### ISSUE TITLE
Window layout: opening windows from commands

### ISSUE THREAD

**Issue by fleimgruber** [abo-abo/hydra#119]
emacs 24.5
hydra 20150328.1015

Given the following hydra
```emacs-lisp
(defhydra hydra-babel (:hint nil
                       :color red)
  "
Babel:^^
----------------------------------
_j_ump to next block
_k_ick back to previous block
_r_esults of block
_o_ther window

"
  ("j" org-babel-next-src-block)
  ("k" org-babel-previous-src-block)
  ("r" org-babel-open-src-block-result)
  ("o" other-window)
  ("q" nil "quit"))
(define-key org-mode-map (kbd "C-M-b") 'hydra-babel/body)
```

I run with vertically split screen, `org-mode` buffer to the left.

Given a babel result line of
```
`#+RESULTS:`
[[file:figures/some.pdf]]
```

running `org-babel-open-src-block-results` from above hydra, the pdf file is opened with `doc-view-mode` in a new window to the right of the hydra tooltips window with the same height as the hydra tooltips window.  I would like to open the results into the right-hand window of the mentioned starting layout - same as would happen with `org-babel-open-src-block-result` without using the hydra.

Illustration:
```
+-----------------------------------+
|                |                  |
| .org buffer    | desired target   |
|                | of `r`           |
|                |                  |
|                |                  |
|                |                  |
|                |                  |
|-----------------------------------+
| hydra tooltips | `r`-opened pdf   |
+-----------------------------------+
```

Am I misconfiguring the hydra?

**Comment by abo-abo** [comment]
> Am I misconfiguring the hydra?

I see that you specified `:color red` in the options, which means that you want to repeat some of the heads more than once (probably <kbd>j</kbd> and <kbd>k</kbd>).  A minor point is that `:color red` is the default option, so it's a bit redundant, but still correct.

One point that might not be correct is `org-babel-open-src-block-result` being also red.  It would greatly simplify things if you made it blue, since then, by the time `org-babel-open-src-block-result` is called, the hydra has already exited and there's no issue with the window config being different.  So you might want to try this:

```elisp
(defhydra hydra-babel (:hint nil
                       :color red)
  "
Babel:^^
----------------------------------
_j_ump to next block
_k_ick back to previous block
_r_esults of block
_o_ther window

"
  ("j" org-babel-next-src-block)
  ("k" org-babel-previous-src-block)
  ("r" org-babel-open-src-block-result :color blue)
  ("o" other-window)
  ("q" nil "quit"))
```

If you still want to keep the <kbd>r</kbd> head red, then you need to re-define `org-babel-open-src-block-result`, since it's using this code:

```elisp
(pop-to-buffer (get-buffer-create "*Org-Babel Results*"))
```

`pop-to-buffer` is pretty random, I have no idea how its algorithm chooses the window.  But `org-babel-open-src-block-result` is very small, you could redefine it. Or file an issue with `org-mode` to get more control on where the buffer is displayed.

**Comment by fleimgruber** [comment]
> I see that you specified :color red in the options, which means that you want to repeat some of the heads more than once (probably j and k). A minor point is that :color red is the default option, so it's a bit redundant, but still correct.

That is correct. Removed the redundant `:color red`.

> One point that might not be correct is org-babel-open-src-block-result being also red. It would greatly simplify things if you made it blue, since then, by the time org-babel-open-src-block-result is called, the hydra has already exited and there's no issue with the window config being different. So you might want to try this:

That is a good idea. It will serve most of the time.

Thanks for the quick response and the fix, will have a look when it's made it to MELPA - keep up the good work.
