### ISSUE TITLE
Refresh lv buffer when only text propertise change

### ISSUE THREAD

**Issue by tarsius** [abo-abo/hydra#121]
In my usage sometimes only text properties change, but because `lv-message` only refreshes the text when `(string= (buffer-string) str)` that isn't enough to update the buffer. Is this optimization really necessary? Or else could you provide a way to force a refresh? I currently use the following kludge:

```lisp
(with-temp-buffer
  (insert ...) ...
  ;; Doesn't work if only properties change:
  ;; (lv-message (buffer-string))
  ;; So make sure the text changes:
  (let ((text (buffer-string)))
    (lv-message "")
    (lv-message text)))
```

A related issue I had while my code still had bugs and did not always properly delete the lv buffer was that `C-x 0` made the lv window go away, but when did bring up the buffer up again, the window was not resized. Again the cause is that the code respective code in `lv-message` did not run as an optimization.

**Comment by abo-abo** [comment]
> Is this optimization really necessary?

It's necessary because the string can be large, and would need to be refreshed after each keystroke.  That can cause (minor) blinking.

Thanks for bringing this up, because my optimization wasn't working for a while due to a change elsewhere. You can now force the update by
let-binding `lv-force-update`.
