### ISSUE TITLE
Prefix command arguments

### ISSUE THREAD

**Issue by vkazanov** [abo-abo/hydra#13]
Some of the functions I want to use as hydra heads can make use of a prefix argument. For example, a few projectile commands accept a `C-u` prefix, thus invalidating project file cache.

Is it possible to do with hydra?

**Comment by abo-abo** [comment]
It's possible to use exactly <kbd>C-u</kbd>, if you follow the approach described [here](http://oremacs.com/2015/01/29/more-hydra-goodness/).
I have yet to figure out how e.g. `digit-argument` should work.

It's important to bind this function instead of a plain `universal-argument`, since `universal-argument` also uses transient map, and there can be only one active at a time:

```
(defun hydra-universal-argument (arg)
  (interactive "P")
  (setq prefix-arg (if (consp arg)
                       (list (* 4 (car arg)))
                     (if (eq arg '-)
                         (list -4)
                       '(4)))))
```

**Comment by vkazanov** [comment]
In my particular case this approach is ok, thank you.

Why not adding the function into the package..? It might be useful in cases similar to mine.

**Comment by abo-abo** [comment]
I'll try to add this soon, but I'm hesitant, because `digit-argument` problem isn't yet solved.

I've made the mistake before, by releasing `hydra-examples.el` prematurely, which I now have to maintain. Using `defhydra` is much better than using `hydra-examples`.

I'm trying now not to release new user-facing functions, unless
they really are a good solution for some problem.
