### ISSUE TITLE
Hydra enforces non-standard function names

### ISSUE THREAD

**Issue by rnkn** [abo-abo/hydra#131]
It appears that `defhydra` creates functions with the name `head/body`, e.g. `hydra-vi/forward-char` instead of `hydra-vi-forward-char`. It seems this naming style is hard-coded. This gives me a slight queasy feeling. It feels a little dictatorial.

I get the whole quasi-namespace thing is all the rage right now, but could you maybe look into letting users define the standard `-` divider?

**Comment by abo-abo** [comment]
> It seems this naming style is hard-coded. This gives me a slight queasy feeling. It feels a little dictatorial.

Hard coding the naming style was (and still is) a reasonable choice. The `-` divider is by no means standard, and no one has complained so far. Hard-coding it to `-` is out of the question, since there are too many references to `/` style, both in sources and documentation.

One more choice is to make the intern call customizable. However, that would increase the byte compilation time for all users of the package, whether they customize the intern or not. This time increase might be negligible, I don't know. If you're willing to make and test this change, feel free to open a PR. Mind the 15 line limit though, unless you already have an Emacs copyright assignment.

**Comment by abo-abo** [comment]
Seems you're not too enthusiastic about making the change happen.  Since I don't like the idea in the first place, and there are no other users to support it, I'll just close the issue.
