### ISSUE TITLE
how to get rid of the blank line in hydra hint

### ISSUE THREAD

**Issue by QiangF** [abo-abo/hydra#134]
Hello sir,
I use emacs on a netbook with small screens, and the blank line in every hydra hint takes 1/25 of my precious screen area. Is it possible to get rid of it?
Thank you!

**Comment by abo-abo** [comment]
I think what you mean by the blank line is the Echo Area. This is the place where Emacs displays warnings and other info.  Hydra doesn't re-use the Echo Area by default, since when a new message comes from Emacs, it hides the current hydra for 2 seconds.  If you think it's a good trade-off, use this code:

```elisp
(setq hydra-lv nil)
```

and hydra will re-use the Echo Area, instead of using a separate area above it.

**Comment by QiangF** [comment]
Thank you sir!
