### ISSUE TITLE
Need help displaying hint

### ISSUE THREAD

**Issue by floli** [abo-abo/hydra#165]
Hello,

Apparently I get the concept of a hint wrong. I want to call search engines on a symbol at point:
```
(defhydra hydra-google (global-map "C-c /" :color blue :hint nil)
  "
_c_: C++
_g_: Google"
  ("c" (lambda ()
         (interactive)
         (flo/start-search "http://en.cppreference.com/mwiki/index.php?title=Special:Search&search=%s"))
   "C++ Reference")
  ("g" (lambda ()
         (interactive)
         (flo/start-search "https://google.de/search?q=%s"))
   "Google")
  ("p" (lambda ()
         (interactive)
         (flo/start-search "https://google.de/search?q=%s site:http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/"))
   "PETSc")
  )
```
But hydra does not display the hint, neither the one from the body, nor that from the heads.

Optimal behavior for me would be that I don't set a body hint and hydra combined the hint from the heads hints and it's key setting, as soon as I type C-c /

Is that possible?

Thanks!

**Comment by floli** [comment]
Ok, found it out shortly after posting. It seems you need to do the keybinding manually not in the defhydra function:

```
(global-set-key (kbd "C-c /") 'hydra-google/body)
```
That wasn't really clear from the docs for me.

Issue could be closed, but maybe you want to improve the docs there.

**Comment by abo-abo** [comment]
OK, I'll look at them again at some point. I'm sure I've written something that relates to using/not using a map, I just can't find it at the moment.

As for your code, I notice that your `:hint nil` doesn't actually do anything, since by assigning a hint to each head you nullify this setting. In order for it to do anything, at least one head needs to be without a hint.

Also, you can skip the lambda wrappers to make things shorter:

```elisp
(defhydra hydra-google (global-map "C-c /" :color blue :hint nil)
  "
_c_: C++
_g_: Google
"
  ("c"
   (message
    "http://en.cppreference.com/mwiki/index.php?title=Special:Search&search=%%s"))
  ("g"
   (message "https://google.de/search?q=%%s")))
```
