### ISSUE TITLE
Single line minibuffer?

### ISSUE THREAD

**Issue by xendk** [abo-abo/hydra#171]
I've created a hydra:

```
(defhydra hydra-window (global-map "C-c w" :color pink)
            "window"
            ;; Dvorak.
            ("c" enlarge-window "enlarge")
            ("h" shrink-window-horizontally "widen")
            ("n" enlarge-window-horizontally "slim")
            ("t" shrink-window "shrink")
            ;; Qwerty.
            ("i" enlarge-window "enlarge")
            ("j" shrink-window-horizontally "widen")
            ("l" enlarge-window-horizontally "slim")
            ("k" shrink-window "shrink")
            ("q" nil "cancel"))
```

Which works fine. However, the minibuffer extends to two lines, which causes an unsightly jump of windows. Seems that it echoes key presses on the second line in some circumstances.

Any way to keep the minibuffer from growing?

**Comment by abo-abo** [comment]
> However, the minibuffer extends to two lines

This is the expected behavior. In fact, the minibuffer is still one line, an additional line is a new window created by `lv-message` function, which works like message.  The reasoning for this is that both the hydra hint, and the called functions compete for the minibuffer, so if e.g. you press <kbd>C-c w c</kbd> with only one window, you'll get an error displayed in the minibuffer, which will shadow the hint.

Still, it's your choice. You can have one line, with the described disadvantage if you customize this var:

```elisp
(setq hydra-lv nil)
```

**Comment by xendk** [comment]
Ah, I see, makes sense. Perhaps I can use pre/post hooks to fiddle with hydra-lv for only this hydra. Or use a wrapping function..

Actually, the temporary shadowing of the hint on error is what I was wishing for. But it doesn't catch errors from outside the hydra, which is understandable. Being able to use other commands while the hydra is active is pretty neat in this case (being able to swap windows without leaving the hydra), but I figure that getting externally generated messages caught would require something like advice'ing the message function: http://www.emacswiki.org/emacs/EchoArea . I might try that out.
