### ISSUE TITLE
FR: Allow doc to be an arbitrary function

### ISSUE THREAD

**Issue by justbur** [abo-abo/hydra#177]
Maybe there is a reason you don't want to do this, but would it be possible to allow specifying a function for the doc that could dynamically generate the hint at the bottom?

**Comment by abo-abo** [comment]
The option is sort-of there. Here's a simple `defhydra`.

```elisp
(defhydra hydra-test ()
  "test"
  ("n" next-line "down"))
```

And here's the relevant part in the macro-expansion:

```elisp
(set
 (defvar hydra-test/hint nil
   "Dynamic hint for hydra-test.")
 '(format
   #("test: [n]: down."
     7 8 (face hydra-face-red))))
```

Since the usage is `(message (eval hydra-test/hint))`, you can put anything you want there by re-defining `hydra-test/hint`.

So the option is there, if you want to do something more advanced. But I'm not sure if anything would be gained by having ability to write:

```elisp
(defhydra hydra-test ()
  (message "test: [n]: down.")
  ("n" next-line "down"))
```

Maybe another form would be better:

```elisp
(defun test-doc ()
  "test: [n]: down.")

(defhydra hydra-test ()
  test-doc
  ("n" next-line "down"))
```

resulting in:

```elisp
(setq hydra-test/hint '(test-doc))
```

Adding this extra syntax would be pretty simple, but all it would do is save you from writing the above line.

**Comment by justbur** [comment]
Thanks for the explanation. I see how to do it now.

The reason I'm asking is that I'd like to test out different methods of automatically generating these hints. Using different rules for faces and possibly automatically adding a color key. I think this would be easiest to do if I could factor out the hint generation into a separate function .

**Comment by abo-abo** [comment]
I see. In that case you'd need to override `hydra--format`.

Here's the relevant part of `defhydra`:

```elisp
(set
 (defvar ,(intern (format "%S/hint" name)) nil
   ,(format "Dynamic hint for %S." name))
 ',(hydra--format name body docstring heads))
```

I don't expect an average user would want to write a function as large as `hydra--format`.  But you can override it with advice:

```elisp
(advice-add 'hydra--format :override 'my-hydra--format)
```

**Comment by justbur** [comment]
Thank you! That's all I need to know I think
