### ISSUE TITLE
Missing hydra key bindings hints

### ISSUE THREAD

**Issue by smithx** [abo-abo/hydra#190]
After commit [Add a shortcut to supply a head's eval-able docstring](https://github.com/abo-abo/hydra/commit/5be27f4b61672a4b8e9dcec2e78bacd1a95fa0d7) hydra don't shows "non-table" hints in hydras with "tables"
Before commit:
![before](https://cloud.githubusercontent.com/assets/2234320/14377758/2a260f3c-fd7a-11e5-8408-d2533df3d876.png)
After commit:
![after](https://cloud.githubusercontent.com/assets/2234320/14377773/3909960e-fd7a-11e5-9dc1-174ad5dabaf1.png)

**Comment by abo-abo** [comment]
Can you please quote your hydra's code? Code > screenshots :)

**Comment by smithx** [comment]
This is example of [Kaushal Modi's projectile hydra](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-projectile.el#L162)

**Comment by joostkremers** [comment]
I suspect I'm being bitten by the same bug. After a recent update, the following hydra doesn't show any hints. All that is displayed is the word `Jump`:

```emacs-lisp
(defhydra jk-hydra-jump (:hint nil)
  "Jump"
  ("SPC" scroll-up-command)
  ("C-v" scroll-up-command)
  ("<backspace>" scroll-down-command)
  ("M-v" scroll-down-command)
  ("g" beginning-of-buffer "Top of buffer")
  ("G" end-of-buffer "End of buffer")
  ("m" (pop-to-mark-command) "Back to mark")
  ("b" bm-toggle "(Un)set bookmark")
  ("t" bm-previous "Previous bookmark")
  ("n" bm-next "Next bookmark"))
```

Before the update, this hydra would show `Jump:` followed by the keys that have hints. The first four keys (`SPC`, `C-v`, `<backspace>`, and `M-v`), are also shown in the hint (without a description, of course). I added the `:hint nil` specification in order to hide those keys completely.

Now, after the update, all the hints and keys are gone. Basically, `:hint` cannot be overridden anymore.

**Comment by abo-abo** [comment]
@joostkremers Thanks, I've added a regression test to ensure your hydra still works.

**Comment by smithx** [comment]
The described bug is reproduced however

**Comment by abo-abo** [comment]
@smithx Oops, sorry. I thought this one was already fixed. Please check again.

**Comment by smithx** [comment]
Thank you! Now it's works
