### ISSUE TITLE
Completely disable the hint for a hydra binding

### ISSUE THREAD

**Issue by der-Daniel** [abo-abo/hydra#196]
Hi,

is it possible to complete hide the hint for a specific hydra binding.
I am using Hydra to switch between windows and do not need any hint since this action is trivial and it just wastes space :)

For Frodo

**Comment by kaushalmodi** [comment]
There was a similar issue like this: https://github.com/abo-abo/hydra/issues/172

You can add `(setq hydra-is-helpful nil)` to completely hide the hydra hints.. or do as recommended in https://github.com/abo-abo/hydra/issues/172#issuecomment-156400237 .

**Comment by der-Daniel** [comment]
great thanks :)

**Comment by abo-abo** [comment]
@der-Daniel @kaushalmodi 

There's a new recommended and more flexible way to set verbosity. It's done independently of the `defhydra` statement.

For example:

1. `(hydra-set-property 'hydra-lispy-x :verbosity 0)` Results in no message at all from `hydra-lispy-x`.
2. `(hydra-set-property 'hydra-lispy-x :verbosity 1)` Results in `lv` not being used, which is nice if your doc is a single line, since then the minibuffer height won't change, which can be distracting for frequent calls.
3. `(hydra-set-property 'hydra-lispy-x :verbosity 2)` Results in `lv` being used.

A new example of doing this is <kbd>x</kbd> (`lispy-x`) from lispy. Doing a single <kbd>x</kbd> shows no doc. Doing <kbd>x?</kbd> shows a minimal doc. Doing <kbd>x??</kbd> shows the full doc.

**Comment by der-Daniel** [comment]
I get `Symbol's function definition is void: hydra-set-property` when I copy this command.
Can I substitute 'hydra-lispy-x with a function defined by `defhydra`?

**Comment by abo-abo** [comment]
> I get Symbol's function definition is void: hydra-set-property when I copy this command.

It's here: https://github.com/abo-abo/hydra/blob/master/hydra.el#L788. You need to use the MELPA version of hydra and update.

> Can I substitute 'hydra-lispy-x with a function defined by defhydra?

Of course, it works for any hydra.

**Comment by der-Daniel** [comment]
Wow thanks, this is even more awesome. :+1:
