### ISSUE TITLE
Feature request: More flexible properties for foreign key handling

### ISSUE THREAD

**Issue by leotaku** [abo-abo/hydra#318]
Currently hydra seems to have a few body-level properties that get run after something happens in the hydra:

- `:post` - run after any non-exiting head is called
- `:after-exit` - run everytime any head is called, including exiting ones

However behavior arround foreign keys seems to be mostly undefined.

Maybe we could have either a specific handle for foreign keys eg. `:foreign-post` or a new option for the `:foreign-keys` property?

Maybe we could also make the `:post` properties more intiutive to use?

So we could have:

- `:post` - stays the same for compatibility
- `:after` - stays the same for compatibility
- `:exit-post` - run for exiting heads
- `:foreign-post` - run for foreign keys
- `:body-post` - run after hydra body

Maybe you would also prefer the second option, and make `:foreign-keys` accept a sexp that takes over the key handling. Although that could probably clutter the interface.

Anyways these are just some of my suggestions for making hydra more general as well as easy to understand, I hope you agree with some of them.

Thanks for making hydra!

**Comment by abo-abo** [comment]
It's not clear for me what you're trying to do. I don't want to over-complicate the interface by things that people rarely use anyway.

With `:foreign-keys`, I think the issue is quite simple: either pass them through without modification, or quit hydra.  This is because `:foreign-keys` are basically all Emacs commands that are not in the current hydra. They have their own `:pre` and `:post` triggers in `pre-command-hook` and `post-command-hook`.

**Comment by leotaku** [comment]
So I have the following issue: 

I the specific hydra I am trying to implement opens and focuses a new buffer. I want to exit said hydra and go back to my initial buffer using foreign keys. However for that to work cleanly I would somehow have to be able to tell hydra to run some code before executing the foreign command. (In this case in order to close the newly-focused buffer)

I should probably have led with a specific example of what I wanted to achieve instead of proposing a design that would (maybe) solve my problem, sorry.

**Comment by abo-abo** [comment]
You can try setting up the `post-command-hook` that looks at `this-command`, uses `symbol-name` and checks if it starts with `hydra-foo...`.

**Comment by MoHKale** [comment]
slightly related issue, how about a value of `quit` for foreign keys as well. Right now you have `nil`, `warn` & `run`. where nil will quit the hydra and then run the key that it was bound to. Quite often I accidentally hit a key that I thought was overridden by the hydra but turns out it wasn't, so the hydra quits & that keys default binding is run (which I wouldn't want to happen). so `quit` would exit the hydra and ignore the keypress. Thoughts?

**Comment by abo-abo** [comment]
> Quite often I accidentally hit a key that I thought was overridden by the hydra but turns out it wasn't, so the hydra quits & that keys default binding is run (which I wouldn't want to happen). so `quit` would exit the hydra and ignore the keypress. Thoughts?

I think you should use `warn` in this case. It warns you, and acts as if you hadn't hit a key by accident.

@leotaku Did you manage your customization? Should I close the issue?

**Comment by leotaku** [comment]
I think I managed to achieve the configuration I wanted, but I no longer remember what I did exactly. In any case, this is no longer relevant to me, so the issue can be closed.

Thank you very much for your help.
