### ISSUE TITLE
How to highlight keys like 0..1 or C-hjkl?

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/hydra#340]
When I use `_0..1_` or `_C-hjkl_` in my docstring, hydra refuses to create the hydra for me. I know this is because they don't match with any of the heads, but sometimes we want such docstring to make it easier to read. Can I use some markup to make `0..1` or `C-hjkl` to have the same color as the keys?

**Comment by MoHKale** [comment]
I'd like a feature like this as well. Not only because of collapsing repetitive key descriptions, but also for when you'd like to emphasize a certain key above others (for example when some predicate it's based on is active). right now I'm trying to create a hydra for workgroups2 which'll show the available workgroups, but I can't find a way to easily emphasize the active workgroup. The solution for now is to simply change the parentheses around the active one and hope that's enough of a visual indicator, but a color shift would also be great.

**Comment by MoHKale** [comment]
oh, also, you can color the 0-1 or hjkl by just specifying the individual bindings seperately. so

"_1_.._9_" will result in 1..9 with 1 and 9 being colored. similairly for hjkl "_h__j__k__l_". Admittedly, I believe you'll recieve a warning of hjkl aren't bound seperately (in your case C-h C-j C-k C-l). I would say, bind hjkl to nil as well. it shouldn't have any adverse consequences... though I'm not sure.

**Comment by AmaiKinono** [comment]
@MoHKale Thanks for your help!

> `_1_.._9_` will result in 1..9 with 1 and 9 being colored.

Yes, this does the thing. I wonder why I didn't realize this.

> similairly for hjkl `_h__j__k__l_`

It's better to have `C-hjkl` highlighted as a whole, which can be achieved by `_C-h__j__k__l_`.

> bind hjkl to nil as well. it shouldn't have any adverse consequences

This makes them work as quit keys. But I can bind them to `ignore`, which does nothing.

**Comment by MoHKale** [comment]
Yeah, thnx, I'm new to hydra so I'm still adjusting to everything. :)

**Comment by abo-abo** [comment]
Looks like the issue is solved. Thanks, @MoHKale. @AmaiKinono if the issue is resolved, please close.

**Comment by MoHKale** [comment]
well, for anyone that's concerned, I figured out how to propertize parts of the text in the hydra hint... turns out, you do it just like you would propertize any other string. I tried it before, but turns out not all faces have `-face` appended to them. Amateur mistake, my bad. Anyways, you can do it like this for example:

```elisp
(defhydra hydra-foo (:hint nil)
  ("a" command-one)
  ("b" command-two)
  ("c" command-three)
  ("d" command-four))

;; for when you're not using the builtin hydra hint syntax
;; (setq hydra-foo/hint
;;       (concat "[_a_] one [_b_] two "
;;               (propertize "[_c_]" 'face 'mode-line)
;;               " three [_d_] four"))

(let ((hint-string (concat "\n[_a_] one [_b_] two "
                           (propertize "[c]" 'face 'mode-line)
                           " three [_d_] four")))
  (setq hydra-foo/hint
        (eval (hydra--format nil
                             '(nil nil :hint nil)
                             hint-string
                             hydra-foo/heads))))
```
Note the initial \n is required... for some reason. Pretty sure I read why in the README.

**Comment by abo-abo** [comment]
@MoHKale Thanks for sharing the info. Here's another solution that's using string literals:

```elisp
(defhydra hydra-test (:hint nil)
  #("
_a_: forward"
    6 13 (face warning))
  ("a" forward-char))
```

If you don't like counting characters, you can produce the hint like so:

```elisp
(concat "\n_a_: " (propertize "forward" 'face 'error))
;; => #("
;; _a_: forward" 6 13 (face error))
```

**Comment by MoHKale** [comment]
Thnx. This entire thing is amazing, I'm grateful for hydras 😄
