### ISSUE TITLE
Hydra with entry hook

### ISSUE THREAD

**Issue by EricCrosson** [abo-abo/hydra#41]
Follow up of http://www.reddit.com/r/emacs/comments/2wg6vy/two_new_hydra_colors_pink_and_teal_or_emacs/corkrnu?context=3

I'm trying to create a hydra that has an 'entry' hook. This differs from a pre hook in that it is only called once, on the initial hydra invocation and not before each head. What do you suppose is the cleanest way to do this?

**Comment by abo-abo** [comment]
Can you show me some starting code of what you're trying to do?
If you want to call some code before `.../body`, currently you could advise it.
If what you're trying to do looks like something others could use, I could add a `:body-pre`.

**Comment by glucas** [comment]
Interesting, I actually thought the intent of :pre was to execute some code once upon starting the hydra, and :post once on exiting. Just found that :pre is being called for every head.

In my case I was looking to save the starting position when the body is first invoked so that I can have one blue head to "quit and return to start" and another to "quit and stay where you are".

**Comment by abo-abo** [comment]
> Interesting, I actually thought the intent of :pre was to execute
> some code once upon starting the hydra, and :post once on
> exiting. Just found that :pre is being called for every head.

I never had any intricate designs with `:pre` or `:post`.
That's why it was working in a simplistic way so far.
I've added `:body-pre`, so now more complex things are possible.

**Comment by glucas** [comment]
Looks good, and your vi example is pretty much exactly what I was doing. Thanks!

**Comment by abo-abo** [comment]
The issue appears to be solved; closing.
