### ISSUE TITLE
Enable to define key-chord when hydra on

### ISSUE THREAD

**Issue by deftsp** [abo-abo/hydra#55]
As a evil user, I bind  key-chord "fd" to a function, which enable me  to escape from insert state and everything else.  So, How can I do that when hydra is active?

I have tryed `(key-chord-define hydra-base-map "df" 'pl/escape-dwim)`  but it not work.

**Comment by abo-abo** [comment]
This can't be done easily.
When the hydra is active, it intercepts all keyboard input.
And `key-chord-define` doesn't treat the keymap in a standard way, so the hydra exits
when <kbd>d</kbd> is pressed, since it's not recognized that it belongs to the hydra.

Try the much easier solution:

```cl
(defun my-escape ()
  (interactive)
  (hydra-keyboard-quit)
  (message "hydra exit"))

(define-key hydra-base-map "q" 'my-escape)
```

Remember that the above has to be done after `(require 'hydra)`, but
before any calls to `defhydra`.

You can even have your longer binding, if you want:

```cl
(define-key hydra-base-map "df" 'my-escape)
```

**Comment by deftsp** [comment]
> This can't be done easily. 

I think so.  Use the method  of following function maybe simpler
```
(evil-define-command cofi/maybe-exit ()
  :repeat change
  (interactive)
  (let ((modified (buffer-modified-p)))
    (insert "k")
    (let ((evt (read-event (format "Insert %c to exit insert state" ?j)
               nil 0.5)))
      (cond
       ((null evt) (message ""))
       ((and (integerp evt) (char-equal evt ?j))
    (delete-char -1)
    (set-buffer-modified-p modified)
    (push 'escape unread-command-events))
       (t (setq unread-command-events (append unread-command-events
                          (list evt))))))))
```

`(define-key hydra-base-map "df" 'my-escape)` will issue unable to bind `d` and `f`.

**Comment by abo-abo** [comment]
I don't understand what you mean by the above code.

**Comment by deftsp** [comment]
For example, If press 'd' without press 'f' in 0.5 second, the 'd' will not be swallow, and it will trigger the command which binding to 'd'.

**Comment by abo-abo** [comment]
If I understood correctly, you want this code:

```cl
(defun foo ()
  (interactive)
  (message "foo"))

(defun bar ()
  (interactive)
  (message "bar"))

(defun wrapper ()
  (interactive)
  (let ((evt (read-event "test" nil 0.5)))
    (if evt
        (call-interactively 'foo)
      (call-interactively 'bar))))

(defhydra test (global-map "C-c")
  ("f" foo "foo")
  ("b" bar "bar")
  ("w" wrapper "test"))
```

But you're just shooting yourself in the foot, in my opinion: for the ability to situationally
call `foo` with a quick <kbd>ww</kbd>, you're sacrificing 0.5s each time you just want to call
`bar` with <kbd>w</kbd>.

And if you call `bar` ahead and then attempt to cancel if there was an
event in the space of 0.5s, it's very bad, since most commands can't
be canceled.

Hydras typically already offer enough keyboard space. There's no need
for keychord shenanigans.

**Comment by deftsp** [comment]
Yes, you got it, as to the space of 0.5s, it can adjust to 0.08s, it work for me.  So I can  escape  from everything with the same key-chord "df".  Since it is difficult to work with key chord and there alternative method , I'll close it now.
