### ISSUE TITLE
hydra binds C-g to foo/hydra-keyboard-quit

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#78]
With the following minimal hydra:

```elisp
(defhydra foo
  (global-map ""
   :post (t))
  "foo"
  ("C-c z" (message "a")))
```
The key <kbd>C-g</kbd> binds to `foo/hydra-keyboard-quit`. Is this expected?

Note the hydra body has `global-map ""`. Same result as having `:bind global-map` in body.

If without `:post`, or with `:post nil`, <kbd>C-g</kbd> binds to `keyboard-quit`.

**Comment by abo-abo** [comment]
> The key C-g binds to foo/hydra-keyboard-quit. Is this expected?

Unexpected, but I should have seen it coming.

This hasn't come up, since `:pre` and `:post` are designed for
hydras wihtout a keymap that are bound through `hydra-hoo/body`.
But I guess they could be useful in other situations too.

`hydra-keyboard-quit` should certainly not be bound in any keymap
outside of hydra. I'll fix this soon.

**Comment by abo-abo** [comment]
Should be fixed now, thanks.
