### ISSUE TITLE
:body-pre called before :post when jumping to another hydra

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#89]
```
(defhydra test-a (:hint nil :post (message "post a"))
  "a"
  ("q" test-b/body "to b" :exit t))

(defhydra test-b (:hint nil :body-pre (message "pre b"))
  "b"
  ("q" nil "exit" :exit t))

(test-a/body)
```

Evaluating that and pressing `q` twice gives these messages:
```
pre b
post a
```

I think post before pre would be easier to reason about.

**Comment by abo-abo** [comment]
I think it actually makes sense as it is now.

Imagine that `test-a` acquires a resource, like the state of being in some window, or changing the
cursor color. It has to release it, so it does it in `:post`.

`test-b` can rely on this resource, so calling `:post` _before_ `test-b/body` doesn't make sense.

Besides, you can see `:body-pre` as basically the initial instruction of `test-b/body`, which is
usually empty.  So <kbd>q</kbd> just calls one of the heads - `test-b/body` and then `:post`, since
that head was exiting. If you forget that `test-b/body` is a hydra, and think of it as just a
function with the `:body-pre` statement inside, it really makes sense.

**Comment by jhonnyseven** [comment]
I have basically that cursor color situation you described. Both `test-a` and `test-b` have different colors. And they both unset any color on exit. If I go from `test-a` to `test-b`, the cursor first changes to `test-b`'s color and then immediately goes off as `test-a`'s `:post` is called.

**Comment by abo-abo** [comment]
How about this solution:

```cl
(defvar color-refcount 0)
(defun set-current-color (&optional color)
  (if color
      (progn
        (set-cursor-color color)
        (cl-incf color-refcount)
        (message "inc ref"))
    (cl-decf color-refcount)
    (message "dec ref")
    (when (<= color-refcount 0)
      (set-cursor-color "black")
      (setq color-refcount 0))))

(defhydra test-a (:body-pre (set-current-color "red")
                  :post (set-current-color))
  "a"
  ("q" test-b/body "to b" :exit t))


(defhydra test-b (:body-pre
                  (set-current-color "green")
                  :post (set-current-color))
  "b"
  ("q" nil "exit" :exit t))


(test-a/body)
```

Each change in color increases the refcount. Each `:post` decreases it.
When refcount becomes zero, the cursor color is reset to default.

**Comment by jhonnyseven** [comment]
That works in this case, thanks :)
